- name: Fetch YouTube Stream
  run: |
    URL="https://www.youtube.com/watch?v=YGEgelAiUf0"

    STREAM=$(yt-dlp -g "$URL" \
      --extractor-args "youtube:player_client=android" | head -n 1)

    echo "Result:"
    echo "$STREAM"

    if [[ "$STREAM" != http* ]]; then
      echo "Failed to fetch stream"
      exit 0
    fi

    echo "#EXTM3U" > manifest.m3u8
    echo "#EXTINF:-1,YouTube Live" >> manifest.m3u8
    echo "$STREAM" >> manifest.m3u8
